//Authentication
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const AUTH_FAILED = 'AUTH_FAILED';
export const FORGOT_PASS = 'FORGOT_PASS';
export const FORGOT_PASS_FAILED = 'FORGOT_PASS_FAILED';
export const RESET_PASS = 'RESET_PASS'
export const RESET_PASS_FAILED = 'RESET_PASS_FAILED'
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const RESET_USER_PROFILE = "RESET_USER_PROFILE";

// Fact Validator
export const FACT_VALIDATION_PROGRESS = 'FACT_VALIDATION_PROGRESS';
export const FACT_VALIDATION_PASS = 'FACT_VALIDATION_PASS';
export const FACT_VALIDATION_FAILED = 'FACT_VALIDATION_FAILED';